name: Build Flarial

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run build.bat
      run: |
        call .\build.bat
      shell: cmd

    - name: Upload DLL
      uses: actions/upload-artifact@v2
      with:
        name: FlarialDLL
        path: "Release/Flarial.dll"
